name: com.amf.alyonamicrofinance
description: Alyona MicroFinance.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  pinput: ^3.0.1
  syncfusion_flutter_datepicker: ^23.1.36
  file_picker: ^5.5.0
  provider: ^6.0.5
  mailer: ^6.0.1
  url_launcher: ^6.1.14
  flutter_email_sender: ^6.0.2
  flutter_mailer: ^2.1.1
  fluttertoast: ^8.2.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconadv1.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono-SemiBold.ttf
        - asset: assets/fonts/RobotoMono-ThinItalic.ttf

permissions:
  android:
    - VIBRATE
